"""Update

Revision ID: 095e01f2b340
Revises: 753712d9c4d3
Create Date: 2026-04-03 11:59:48.834563

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '095e01f2b340'
down_revision = '753712d9c4d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libraryplant',
    sa.Column('common_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('latin_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('overview', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('spring_care', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summer_care', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('autumn_care', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('winter_care', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminder',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('type', sa.Enum('watering', 'pruning', 'feeding', 'general', name='remindertype'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.Column('repeat', sa.Enum('once', 'weekly', 'monthly', name='reminderrepeat'), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('document')
    op.add_column('garden', sa.Column('garden_code', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False))
    op.add_column('garden', sa.Column('created_by', sa.Uuid(), nullable=False))
    op.alter_column('garden', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_garden_garden_code'), 'garden', ['garden_code'], unique=True)
    op.drop_constraint(op.f('garden_owner_id_fkey'), 'garden', type_='foreignkey')
    op.create_foreign_key(None, 'garden', 'user', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'garden', 'user', ['created_by'], ['id'])
    op.drop_column('garden', 'description')
    op.drop_column('garden', 'location')
    op.add_column('plant', sa.Column('common_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('plant', sa.Column('overview', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('plant', sa.Column('spring_care', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('plant', sa.Column('summer_care', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('plant', sa.Column('autumn_care', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('plant', sa.Column('winter_care', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('plant', sa.Column('library_plant_id', sa.Uuid(), nullable=True))
    op.alter_column('plant', 'latin_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key(None, 'plant', 'libraryplant', ['library_plant_id'], ['id'], ondelete='SET NULL')
    op.drop_column('plant', 'planted_at')
    op.drop_column('plant', 'maintenance_advice')
    op.drop_column('plant', 'name')
    op.drop_column('plant', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('plant', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('plant', sa.Column('maintenance_advice', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('plant', sa.Column('planted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'plant', type_='foreignkey')
    op.alter_column('plant', 'latin_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('plant', 'library_plant_id')
    op.drop_column('plant', 'winter_care')
    op.drop_column('plant', 'autumn_care')
    op.drop_column('plant', 'summer_care')
    op.drop_column('plant', 'spring_care')
    op.drop_column('plant', 'overview')
    op.drop_column('plant', 'common_name')
    op.add_column('garden', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('garden', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'garden', type_='foreignkey')
    op.drop_constraint(None, 'garden', type_='foreignkey')
    op.create_foreign_key(op.f('garden_owner_id_fkey'), 'garden', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_garden_garden_code'), table_name='garden')
    op.alter_column('garden', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('garden', 'created_by')
    op.drop_column('garden', 'garden_code')
    op.create_table('document',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('garden_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['garden.id'], name=op.f('document_garden_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('document_pkey'))
    )
    op.drop_table('reminder')
    op.drop_table('libraryplant')
    # ### end Alembic commands ###
